version: "2.1"
services:
    rpisec-test-auth-db:
        container_name: rpisec-test-auth-db
        image: tobi312/rpi-postgresql:9.6
        environment:
            - POSTGRES_USER=rpisec-auth
            - POSTGRES_PASSWORD=rpisec-auth
            - POSTGRES_DATABASE=rpisec-auth
        mem_limit: 64m
        cpu_shares: 2
    rpisec-test-app-db:
        container_name: rpisec-test-app-db
        image: tobi312/rpi-postgresql:9.6
        environment:
            - POSTGRES_USER=rpisec-app
            - POSTGRES_PASSWORD=rpisec-app
            - POSTGRES_DATABASE=rpisec-app
        mem_limit: 64m
        cpu_shares: 2
    rpisec-test-auth:
        container_name: rpisec-test-auth
        build:
            context: ./auth
        environment:
            - OAUTH_JAVA_OPTS=-Xms128m -Xmx256m
            - WAIT_INTERVAL=5
        volumes:
            - ./volumes/log:/home/user/log
        mem_limit: 256m
        cpu_shares: 4
        depends_on:
            - rpisec-test-auth-db
            - rpisec-test-app
    rpisec-test-app:
        container_name: rpisec-test-app
        build:
            context: ./app
        environment:
            - APP_JAVA_OPTS=-Xms128m -Xmx256m
            - WAIT_INTERVAL=5
        volumes:
            - ./volumes/log:/home/user/log
        mem_limit: 256m
        cpu_shares: 4
        depends_on:
            - rpisec-test-app-db
    rpisec-test-nginx:
        container_name: rpisec-test-nginx
        build:
            context: ./nginx
        volumes:
            - ./volumes/log:/var/log/nginx/
        mem_limit: 64m
        cpu_shares: 4
        ports:
            - 9080:8080
        depends_on:
            - rpisec-test-app-db
            - rpisec-test-auth-db
            - rpisec-test-app
            - rpisec-test-auth